services:
  frontend:
    build:
      context: .
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./src:/code/src
      - ./tailwind.config.js:/code/tailwind.config.js
    environment:
      - DISABLE_ESLINT_PLUGIN=true                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
