default_agent: website_agentV2
agents:
  website_agentV2:
    name: website_agentV2
    entrypoint: /Users/sushensatturu/PersonalRepos/my-website/agent-service/src/main.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: /Users/sushensatturu/PersonalRepos/my-website/agent-service/src
    aws:
      execution_role: arn:aws:iam::136079914867:role/AmazonBedrockAgentCoreSDKRuntime-ap-southeast-2-bf52e6b2d4
      execution_role_auto_create: false
      account: '136079914867'
      region: ap-southeast-2
      ecr_repository: 136079914867.dkr.ecr.ap-southeast-2.amazonaws.com/bedrock-agentcore-website_agentv2
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: website_agentV2-ZY35by5UAQ
      agent_arn: arn:aws:bedrock-agentcore:ap-southeast-2:136079914867:runtime/website_agentV2-ZY35by5UAQ
      agent_session_id: 989a962e-b3be-4496-a208-c3530f7254aa
    codebuild:
      project_name: bedrock-agentcore-website_agentv2-builder
      execution_role: arn:aws:iam::136079914867:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-southeast-2-bf52e6b2d4
      source_bucket: bedrock-agentcore-codebuild-sources-136079914867-ap-southeast-2
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
